
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GameOfLife;

import gui.Window;
// import board.*;

public class App {

    static State currState = State.PAUSED;

    public static void main(String[] args) {
        Window window = new Window("Ciao", 1000, 1000);
        board.VisualBoard b = new board.VisualBoard(new board.ThreadedBoard(100, 100, 16, 2048), window);
        window.open();
        b.init();
        while (window.isOpen()) {
            currState = Input.getNextState(b, currState);
            if (currState == State.RUNNING) {
                b.update();
                b.render();
                Output.printState(b, currState);
            } else if (currState == State.DRAWING) {
                Input.getDrawingInput(b);
                b.render();
                Output.printState(b, currState);
            } else if (currState == State.PAUSED) {
                Input.steppedExecution(b);
                b.render();
                Output.printState(b, currState);
            }
            window.refreshAndClear();
        }
    }

    
}
